//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LSPDebuggingTool.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LSPDebuggingTool.Localization.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 拓展LSP请求.
        /// </summary>
        public static string Expand_LSP_Requests {
            get {
                return ResourceManager.GetString("Expand_LSP_Requests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 通用LSP请求.
        /// </summary>
        public static string Generic_LSP_Requests {
            get {
                return ResourceManager.GetString("Generic_LSP_Requests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LSP应答记录.
        /// </summary>
        public static string LSP_Answer_Record {
            get {
                return ResourceManager.GetString("LSP_Answer_Record", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LSP Server 工作台.
        /// </summary>
        public static string LSP_Operation_Record_Tab_Name {
            get {
                return ResourceManager.GetString("LSP_Operation_Record_Tab_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LSP Server 启动与初始化.
        /// </summary>
        public static string LSP_Startup_Parameters {
            get {
                return ResourceManager.GetString("LSP_Startup_Parameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LSP Client 工作区.
        /// </summary>
        public static string LSP_Workspace_Tab_Name {
            get {
                return ResourceManager.GetString("LSP_Workspace_Tab_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 打开附属信息文件.
        /// </summary>
        public static string Open_Ancillary_Information_File {
            get {
                return ResourceManager.GetString("Open_Ancillary_Information_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请求参数编辑.
        /// </summary>
        public static string Request_Parameter_Editing {
            get {
                return ResourceManager.GetString("Request_Parameter_Editing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 保存附属信息文件.
        /// </summary>
        public static string Save_Ancillary_Information_File {
            get {
                return ResourceManager.GetString("Save_Ancillary_Information_File", resourceCulture);
            }
        }
    }
}
