namespace AvaloniaEditLSPIntegration;

public static class GeneralMethod
{
    public const string textDocument_didOpen = "textDocument/didOpen";
    public const string textDocument_didChange = "textDocument/didChange";
    public const string textDocument_didClose = "textDocument/didClose";
    public const string textDocument_willSave = "textDocument/willSave";
    public const string textDocument_willSaveWaitUntil = "textDocument/willSaveWaitUntil";
    public const string textDocument_didSave = "textDocument/didSave";
    public const string textDocument_didChangeConfiguration = "textDocument/didChangeConfiguration";
    public const string textDocument_didChangeWatchedFiles = "textDocument/didChangeWatchedFiles";
    public const string textDocument_symbol = "textDocument/symbol";
    public const string textDocument_codeAction = "textDocument/codeAction";
    public const string textDocument_completion = "textDocument/completion";
    public const string completionItem_resolve = "completionItem/resolve";
    public const string textDocument_hover = "textDocument/hover";
    public const string textDocument_signatureHelp = "textDocument/signatureHelp";
    public const string textDocument_declaration = "textDocument/declaration";
    public const string textDocument_definition = "textDocument/definition";
    public const string textDocument_typeDefinition = "textDocument/typeDefinition";
    public const string textDocument_implementation = "textDocument/implementation";
    public const string textDocument_references = "textDocument/references";
    public const string textDocument_documentHighlight = "textDocument/documentHighlight";
    public const string textDocument_documentSymbol = "textDocument/documentSymbol";
    public const string textDocument_codeActionResolve = "textDocument/codeAction/resolve";
    public const string textDocument_codeLens = "textDocument/codeLens";
    public const string codeLens_resolve = "codeLens/resolve";
    public const string textDocument_codeLens_resolve = "textDocument/codeLens/resolve";
    public const string textDocument_documentLink = "textDocument/documentLink";
    public const string documentLink_resolve = "documentLink/resolve";
    public const string textDocument_documentLink_resolve = "textDocument/documentLink/resolve";
    public const string textDocument_documentColor = "textDocument/documentColor";
    public const string textDocument_colorPresentation = "textDocument/colorPresentation";
    public const string textDocument_formatting = "textDocument/formatting";
    public const string textDocument_rangeFormatting = "textDocument/rangeFormatting";
    public const string textDocument_onTypeFormatting = "textDocument/onTypeFormatting";
    public const string textDocument_rename = "textDocument/rename";
    public const string textDocument_prepareRename = "textDocument/prepareRename";
    public const string textDocument_foldingRange = "textDocument/foldingRange";
    public const string textDocument_selectionRange = "textDocument/selectionRange";
    public const string textDocument_linkedEditingRange = "textDocument/linkedEditingRange";
    public const string textDocument_callHierarchy = "textDocument/callHierarchy";
    public const string callHierarchy_incomingCalls = "callHierarchy/incomingCalls";
    public const string callHierarchy_outgoingCalls = "callHierarchy/outgoingCalls";
    public const string textDocument_semanticTokens_full = "textDocument/semanticTokens/full";
    public const string textDocument_semanticTokens_fullDelta = "textDocument/semanticTokens/full/delta";
    public const string textDocument_semanticTokens_range = "textDocument/semanticTokens/range";
    public const string textDocument_prepareCallHierarchy = "textDocument/prepareCallHierarchy";
    public const string textDocument_prepareCallHierarchy_resolve = "textDocument/prepareCallHierarchy/resolve";
    public const string textDocument_selectionRange_resolve = "textDocument/selectionRange/resolve";
    public const string textDocument_linkedEditingRange_resolve = "textDocument/linkedEditingRange/resolve";
    public const string textDocument_publishDiagnostics = "textDocument/publishDiagnostics";
}